<Project Sdk="Microsoft.NET.Sdk">


<PropertyGroup>

    <OutputType>WinExe</OutputType>


    <TargetFramework>
        net8.0-windows
    </TargetFramework>


    <UseWPF>true</UseWPF>


    <Nullable>enable</Nullable>


    <ImplicitUsings>enable</ImplicitUsings>



    <!-- APP NAME -->

    <AssemblyName>
        NG PB Launcher
    </AssemblyName>


    <RootNamespace>
        NGPB.Launcher
    </RootNamespace>



    <!-- WINDOWS BUILD -->

    <RuntimeIdentifier>
        win-x64
    </RuntimeIdentifier>


    <PlatformTarget>
        x64
    </PlatformTarget>


    <SelfContained>
        true
    </SelfContained>


    <PublishSingleFile>
        true
    </PublishSingleFile>



    <!-- OPTIMIZATION -->

    <PublishReadyToRun>
        true
    </PublishReadyToRun>


    <EnableCompressionInSingleFile>
        true
    </EnableCompressionInSingleFile>



    <!-- VERSION -->

    <Version>
        1.0.0
    </Version>


    <AssemblyVersion>
        1.0.0.0
    </AssemblyVersion>


    <FileVersion>
        1.0.0.0
    </FileVersion>



</PropertyGroup>





<ItemGroup>


    <!-- IMAGE ASSETS -->

    <Resource Include="Assets\logo.png"/>

    <Resource Include="Assets\user.png"/>

    <Resource Include="Assets\server.png"/>

    <Resource Include="Assets\update.png"/>




    <!-- VIDEO -->

    <Content Include="Assets\background.mp4">

        <CopyToOutputDirectory>
            PreserveNewest
        </CopyToOutputDirectory>

    </Content>



</ItemGroup>





</Project>
